GraphFilter/GraphFilter

src/controller/wizard_controller.py, src/store/data_dictionary.json, src/store/invariants_store.py, src/store/operations_and_invariants/bool_invariants.py, src/store/operations_and_invariants/invariants.py, src/store/operations_and_invariants/num_invariants.py, src/store/operations_and_invariants/operations.py, test/domain/unit_tests.py
Refactor some variable in invariants and operations class;
On equation page (wizard), will be insert '()' after invariants and operations that works as a function;
Implementation of 'selfcomplementary' and 'cubic' in boolean invariants.
Closes #89
=> Refactor and new invariants

resources/data/data_dictionary.json, source/controller/project_controller.py, source/domain/equation.py, source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/operations.py, test/domain/unit_tests.py
=> Some fixes in invariants when the input graph is trivial

source/controller/project_controller.py, source/store/operations_and_invariants/bool_invariants.py, source/store/operations_and_invariants/invariants.py, source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py, source/view/project/docks/graph_information_dock.py, test/domain/unit_tests.py
=> 113 refactor print of invariants on visualization

source/controller/controller.py, source/store/operations_and_invariants/invariants.py, source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py
=> 126 bug export graph6

requirements.txt, source/domain/equation.py
=> 116 problem of matching number of graph

requirements.txt, source/controller/controller.py, source/domain/exports.py, source/view/project/project_window.py
Reverts GraphFilter/GraphFilter#138
=> Revert "133 export graphs to a sheet file"

requirements.txt, source/controller/controller.py, source/domain/exports.py, source/view/project/project_window.py
This branch is a duplicate of 133 with a fix on requirements.txt.
Closes #133
=> Export to sheet implemented

source/view/project/docks/invariants_checks_dock.py
=> Search bar implemented

source/view/project/docks/invariants_checks_dock.py, source/view/wizard/pages/project_information_page.py
=> 155 bug behavior search bar invariants dock

source/view/project/docks/visualize_graph_dock.py
=> Block drawing methods

source/controller/project_controller.py, source/domain/utils.py, source/view/project/project_window.py, source/view/welcome/welcome_window.py, source/view/wizard/pages/conditions_page.py, source/view/wizard/pages/method_page.py, source/view/wizard/pages/project_information_page.py, source/view/wizard/wizard_window.py
=> 165 screen responsivity

source/controller/wizard_controller.py, source/domain/utils.py
=> 166 change default folder

source/controller/wizard_controller.py
=>  Wizard help button crashes

source/view/wizard/wizard_window.py
=> Fix minimization error

source/controller/wizard_controller.py
=> Fix update conditions bug

source/view/welcome/welcome_content.py
=> Update version number main window

source/controller/wizard_controller.py
=> Crash on add project description

source/view/project/docks/visualize_graph_dock.py
=> Unblock graph drawing

source/view/project/docks/visualize_graph_dock.py
=> Set limitations to draw graph

source/view/project/docks/visualize_graph_dock.py
=> Implementing node label view

source/controller/project_controller.py, source/view/project/docks/tree_file_dock.py
=> Customization of the file tree

source/controller/project_controller.py, source/view/project/docks/visualize_graph_dock.py, source/view/project/project_tool_bar.py
=> Implementation Operations in toolbar

requirements.txt
=> Support for graphs with no edges

source/view/project/docks/visualize_graph_dock.py
=> Fix first vertex without id bug

source/controller/controller.py
=> Tree file view funcionality

source/controller/project_controller.py
=> Update on the graph plot

source/store/operations_and_invariants/other_invariants.py
=> Fix Eigenvector Centrality

source/controller/project_controller.py, source/view/project/docks/visualize_graph_dock.py
=> Display alert box on invalids graphs

source/controller/project_controller.py
=> Insert universal vertex button

source/controller/controller.py, source/controller/project_controller.py, source/store/project_information_store.py, source/view/project/project_tool_bar.py
=> Delete button functionality

source/controller/controller.py, source/controller/project_controller.py, source/store/project_information_store.py
=> Save button functionality

source/controller/project_controller.py, source/controller/wizard_controller.py, source/domain/utils.py, source/store/new_graph_store.py, source/view/components/new_graph_dialog.py
=> Design new graph window

source/store/operations_and_invariants/invariants.py, source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py
=> Smallest eigenvalue of a matrix associated with a graph

source/store/operations_and_invariants/bool_invariants.py, source/store/operations_and_invariants/invariants.py, source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py
=> Eccentricity invariants of a graph

source/controller/project_controller.py, source/controller/wizard_controller.py, source/domain/utils.py, source/store/new_graph_store.py, source/view/components/new_graph_dialog.py
=> Validation of new graph parameters

source/controller/project_controller.py, source/view/project/docks/visualize_graph_dock.py
=> Update invariants dock

source/domain/utils.py, source/view/project/docks/visualize_graph_dock.py
=> Restarting vertexes labels

source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py
=> Implementing eccentricity matrix

source/controller/project_controller.py
=> Bug on change graph with invariants

source/controller/controller.py, source/controller/wizard_controller.py, source/store/project_information_store.py, source/view/wizard/pages/method_page.py
=> Blank project option

source/controller/wizard_controller.py, source/view/wizard/pages/files_page.py
=> New download button inserted

source/controller/project_controller.py, source/store/new_graph_store.py, source/view/project/docks/visualize_graph_dock.py
=> Layout to new graph

source/domain/filter_list.py
=> Filtering with invalid files

source/domain/utils.py, source/store/new_graph_store.py, source/view/project/docks/visualize_graph_dock.py
=> Fix bug on empty graph

source/controller/controller.py, source/view/project/docks/tree_file_dock.py, source/view/project/project_window.py
=> Updated file export and menu

source/controller/project_controller.py, source/view/project/project_window.py
=> Update restore view for the tree file

source/controller/controller.py, source/controller/project_controller.py
=> Project window restore with cancel new project

source/controller/controller.py, source/controller/filter_controller.py, source/controller/project_controller.py, source/controller/wizard_controller.py, source/domain/utils.py, source/store/new_graph_store.py, source/store/project_information_store.py, source/view/project/docks/tree_file_dock.py, source/view/project/docks/visualize_graph_dock.py
Closes #307 
>At this point I took the opportunity to add a system to show in the project window title with the name of the current open file. This would be a future issue but since it is a small modification, it was anticipated in this issue.
=> Refactor project information store

source/controller/controller.py
Fixed bugs found when exporting folders or files that did not contain graphs.
=> Bugfixes in exports

source/controller/project_controller.py, source/domain/utils.py, source/store/new_graph_store.py
=> Implement Threshold in ```New Graph```

source/controller/project_controller.py
=> Fix bug on universal vertex with none graph

source/controller/controller.py, source/controller/filter_controller.py, source/controller/project_controller.py, source/controller/wizard_controller.py, source/domain/utils.py, source/store/export_graph_to.py, source/view/components/message_box.py, source/view/wizard/pages/files_page.py
=> Optimization of controller methods

source/view/project/project_tool_bar.py
=> Limit name of file in toolbar

source/view/components/message_box.py
=> Bug fixes in loading gif window

source/domain/utils_file.py
=> Fix bug on open gml file from tree

source/controller/wizard_controller.py, source/store/operations_and_invariants/num_invariants.py
=> Two tabs to spectral invariants

source/domain/utils_file.py, source/store/export_graph_to.py
=> Program freezes when export to g6 or txt

source/controller/project_controller.py, source/domain/utils_file.py
=> Delete graph function with. gml

source/domain/pdf_model.py
=> Change logo path on pdf model

source/controller/project_controller.py
=> Disable combo on gml graphs from tree

source/controller/project_controller.py
Closes #362 
New section in Wiki: https://github.com/GraphFilter/GraphFilter/wiki/User-Guide#problems-and-suggestions
Templates for issues: https://github.com/GraphFilter/GraphFilter/issues/new/choose
=> Template new issue for user

source/controller/project_controller.py, source/view/loading/loading_gif.py
=> Fix double click folder bug

source/controller/controller.py, source/controller/project_controller.py
=> Fix bug on start blank project

source/controller/controller.py, source/controller/project_controller.py, source/domain/utils.py, source/domain/utils_file.py, source/view/project/docks/visualize_graph_dock.py, source/view/project/project_tool_bar.py, source/view/project/project_window.py
=> Mac problems pre release

source/controller/controller.py, source/controller/project_controller.py, source/domain/utils.py, source/domain/utils_file.py, source/store/new_graph_store.py, source/view/project/project_tool_bar.py
=> Bugs on plotting some graphs

source/store/operations_and_invariants/num_invariants.py, source/store/operations_and_invariants/other_invariants.py, test/domain/unit_tests.py
=> Implement chromatic index

app.py, source/controller/controller.py, source/store/operations_and_invariants/num_invariants.py, source/view/project/about_window.py, source/view/welcome/welcome_content.py
Closes #388 
Before approving, **generate the executable** and test the following filtering (using executable):
_Equation_ `μ₁(Ƙ(G))+λ₂(ℓ(G))>0` (you can use copy-paste) and [this imput file](https://houseofgraphs.org/data/cographs/cographConnected11.g6)
=> Problem to multiprocessing in executabe

source/domain/utils_file.py, source/view/project/docks/visualize_graph_dock.py
=> Fix the writing of a new graph in a g6 file

source/store/operations_graph.py
=> Bug on `Inverse Line Graph`

source/store/new_graph_store.py, source/view/project/docks/visualize_graph_dock.py
Closes #394 
> **Warning**
> It's been a significant change, so if you can, please test it calmly
=> Graph plotting problem

source/domain/exports.py, source/view/project/project_tool_bar.py
=> Graph count on combo box start at 1

source/controller/controller.py, source/domain/utils_file.py, source/store/export_graph_to.py, source/store/project_information_store.py
=> Add default name and folder to export excel file

source/controller/controller.py
=> Set title bar when showing project window

source/store/help_button_text.py, source/view/wizard/pages/review_page.py
=> Update wizard helper texts

source/controller/wizard_controller.py, source/view/wizard/pages/files_page.py
=> Crash on change graph file
